#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M4{1,0,5.2,5
#
certflasher.xem4: package/cfg/certflasher.xem4.mak

clean::
	-$(RM) package/cfg/certflasher.xem4.mak
